### ISSUE TITLE
postProcessResponse doesn't work when raw is an array of integers

### ISSUE THREAD

**Issue by bostrom** [Kequc/knex-stringcase#1]
E.g. when doing inserts to postgresql the raw response is an array of the inserted ids (`[12]`). The case conversion breaks the response when trying to convert the keys of the array.

**Comment by Kequc** [comment]
I did not see this until now. Sorry, notifications must have missed me. I'm happy to accept a change like this, I've just never run into it before.

Could you provide an example scenario?

**Comment by Kequc** [comment]
I decided to take your word for it. 👍 Implemented in `0.2.1`

**Comment by bostrom** [comment]
Sorry for the delay. So per the knex documentation https://knexjs.org/#Builder-returning 

`.returning('id')` in postgresql returns `[1]` or `[1,2]` for multiple rows
`.rerturning(['id', 'name']) in postresql returns `[{id: 1, name: 'John'}]`

Before this issue was fixed, the keyConvert function would assume that the array `[1]` contains an object.
