### ISSUE TITLE
Create TypeScript definitions

### ISSUE THREAD

**Issue by ryanep** [Kequc/knex-stringcase#13]
First of all, thanks for the module. 

It would be good to create TypeScript definitions for this.

Happy to contribute.

**Comment by Kequc** [comment]
Hi there, I don't know about this because really there's no interaction with the module. It's just passed an object and returns an object.

Can you give an example of a use case where `any` is insufficient? I just don't want to bog the module down with anything it doesn't need. Thank you.

**Comment by Kequc** [comment]
Closing for now. Again I'm not opposed to the idea just looking for more information.

**Comment by shellscape** [comment]
FWIW `any` is _never ever ever_ sufficient and is only a part of TypeScript for legacy compatibility.
