### ISSUE TITLE
How to stop converting table name?

### ISSUE THREAD

**Issue by fondberg** [Kequc/knex-stringcase#22]
I love this plugin but I have a problem with it converting table names such as "order-rows_fields" to "order_rows_fields".
Is there a way to stop this for table names but keep it for column names?

**Comment by Kequc** [comment]
The table name passes through the `wrapIdentifier` function the same as column names do, this is part of knex. I'm not sure how you could do what you want other than to set your `wrapIdentifier` method. Something like:

```
{
  wrapIdentifier (output, origImpl) {
    if (output === 'order_rows_fields') {
      return origImpl('order-rows_fields');
    }
    return origImpl(output);
  }
}
```

Or set your `stringcase` attribute. Something like:

```
{
  stringcase: ['snakecase', (output) => {
    if (output === 'order_rows_fields') {
      return 'order-rows_fields';
    }
    return output;
  }]
}
```

Unfortunately there's no way to distinguish between table names and columns from my understanding. Knex is just going to pass everything through the same method.
