### ISSUE TITLE
column name in camelCase doesn't work with knex pluck

### ISSUE THREAD

**Issue by maxorcist** [Kequc/knex-stringcase#23]
When plucking, snakecase vs camelcase returns different results:
        knex('tablename').pluck('user_id')   >   [2, 3]
        knex('tablename').pluck('userId')   >   [undefined, undefined]

**Comment by Kequc** [comment]
That's interesting, knex is not using `wrapIdentifier` in this function. Not to shirk responsibility but I suppose this should be an issue directed at the knex library, as there's nothing I can do about it.

**Comment by maxorcist** [comment]
Ah! Alright, thank you for the answer.
