### ISSUE TITLE
When writing queries using pure knex.raw() statements results are not camelcased

### ISSUE THREAD

**Issue by jesselathamdev** [Kequc/knex-stringcase#25]
Hi again,

I'm mostly looking for confirmation here regarding knex-stringcase whether it definitively converts pure knex.raw() queries to camelcase.  

For the local testing I've worked through after pulling knex-stringcase into our project we can clearly see that one knex query which uses `knex('table_name').select('column_one', 'column_two')` returns the field names as camelcase, yet when using the exact same query but with `knex.raw('select column_one, column_two from table_name')` any field names returned are in snakecase.

The team and I here are wondering if this a bug or is this by design?

**Expected results:**
When using pure knex.raw('select column_one, column_two from table_name') queries the field names are returned as camelcase

**Actual results:**
When using pure knex.raw('select column_one, column_two from table_name') queries the field names are returned as snakecase

**Versions:**
* knex-stringcase: 1.4.6
* knex: 1.0.3
* postgresql v13
* node-postgres: 8.7.3
* node: 16.13.1
* npm: 8.1.2

**Comment by Kequc** [comment]
The library is very simple in operation, it only makes use of built in knex configuration options. Specifically `postProcessResponse` and `wrapIdentifier`.

http://knexjs.org/#Installation-post-process-response http://knexjs.org/#Installation-wrap-identifier

The behavior will be identical to not using the library, just knex directly. The `knex` library is responsible for deciding when to use these configuration options. It seems that when using `knex.raw` that isn't the case, it will not make any changes to raw queries and responses.

As an aside. With this library you can use `knex('tableName').select('columnOne', 'columnTwo')` in place of `knex('table_name').select('column_one', 'column_two')`, but this might not be related to your question. I just thought I'd mention.

Based on the behavior you are describing I don't think `knex.raw('select columnOne, columnTwo from tableName')` would work.

**Comment by jesselathamdev** [comment]
Thanks Kequc.  

Without pushing on the actual knex side, we're willing here to accept the pure knex.raw() should not have transformation pipelines applied to it and that it would be left to ourselves to convert or operate on the results (and that there's nothing that you or knex-stringcase can do).  As a workaround or actual solution perhaps is to call the respective method from knex-stringcase directly on the result on a case-by-case basis will do what we need.  Not a bad idea actually for us to create a small util wrapper within our app scope to help with this and hide the concern away.

Thanks also for the hint of using camelcase within the select itself, I hadn't got to that point yet, but we do find some value in being able to copy/paste out the parts of the query to our db tool of choice and reconstruct with proper SQL keywords.

I think you can consider this ticket closed as I have the answers I need here.  Cheers!

**Comment by Kequc** [comment]
That's a definite consideration, why not expose the internals. Something similar to.

```
const { postProcessResponse } = require('knex-stringcase');
```

So that you could run the result through it manually. Is this what you meant?

**Comment by Kequc** [comment]
I haven't done much testing with it, I'm not next to my computer but it seems knex exposes something called `userParams` to it's instance.

https://github.com/knex/knex/blob/master/lib/knex-builder/Knex.js

I wonder if there's something in there like `knex.userParams.postProcessResponse` that you could use to do exactly what you are asking for.

**Comment by Kequc** [comment]
closing because this is built into the core of knex and cannot do anything about it :)

**Comment by Kequc** [comment]
Don't mean to bring up an old topic after such a long time but you can do the following.

```javascript
const { wrapIdentifier, postProcessResponse } = knexStringcase();

const db = knex({
  client: 'mysql',
  connection: {
    host: '127.0.0.1',
    user: 'your_database_user',
    password: 'your_database_password',
    database: 'myapp_test'
  },
  wrapIdentifier,
  postProcessResponse,
});

export { db, postProcessResponse };
```

Then use postProcessResponse.

```javascript
const rawResult = await knex.raw('select column_one, column_two from table_name');
const result = postProcessResponse(rawResult);
```

That will do essentially the same thing as what knex does when you are using regular (not raw) queries. You can't quite also use wrapIdentifier in the same way, because internally knex passes something called `origImpl` as a second parameter. If you could it might be able to be used something like this.

```javascript
const rawQuery = `
  select ${wrapIdentifier('columnOne')}, ${wrapIdentifier('columnTwo')}
  from ${wrapIdentifier('tableName')}
';

const rawResult = await knex.raw(rawQuery);
const result = postProcessResponse(rawResult);
```

If I was able to make a version that didn't require the second parameter, would this be a useful feature?

----

https://knexjs.org/guide/raw.html

The official documentation provides an example like this:

```javascript
const raw = ':name: = :thisGuy or :name: = :otherGuy or :name: = :undefinedBinding';

knex('users').where(
  knex.raw(raw, {
    name: 'users.name',
    thisGuy: 'Bob',
    otherGuy: 'Jay',
    undefinedBinding: undefined,
  })
);
```

I don't have time right now to try it but I wonder if identifiers are converted when using the `:identifier:` syntax.
