### ISSUE TITLE
1.0.0 -> 1.0.1 processing of dates

### ISSUE THREAD

**Issue by brandonburkett** [Kequc/knex-stringcase#6]
With 1.0.0, timestamptz columns returned an instance of `Date`, but with 1.0.1, they return a plain object.  For now, I am pinning to 1.0.0.

-----

## 1.0.0

console.log(lastItem.createdAt);
```
2018-12-05T16:16:01.841Z 
```

console.log(typeof lastItem.createdAt);
```
object
```

console.log(lastItem.createdAt instanceof Date);
```
true
```

-----

## 1.0.1

console.log(lastItem.createdAt);
```
{}
```

console.log(typeof lastItem.createdAt);
```
object
```

console.log(lastItem.createdAt instanceof Date);
```
false
```

-----

My package.json includes:
```
    "pg": "^7.8.2",
    "knex": "^0.16.3",
    "knex-stringcase": "1.0.1",
```

**Comment by Kequc** [comment]
This issue is caused by recursive traversal of the result. I will do a release today.

**Comment by Kequc** [comment]
You were absolutely right. Dates are being processed correctly in 1.0.2

**Comment by Zjaaspoer** [comment]
I'm still having this issue in `1.0.2` unfortunately when using this code to convert all dates to a moment:

`types.setTypeParser(1184, moment)`

it looks like the prototype is being reset to a normal object

**Comment by Kequc** [comment]
In order to support deep data structures the columns are being converted recursively. It looks for an object and if it is an object it converts it. I've made an explicit exception for `Date` objects. I didn't consider what happens when you use something else like moment.

Would another configuration option that allows you to create more exceptions work? Something like.

```
{
    ignoreObjects: [obj => obj.isMoment]
}
```

If the variable is an object then it will run through your exceptions, and skip conversion if any function returns truthy?

**Comment by Kequc** [comment]
I've added the `ignoreStringcase` configuration option in 1.0.3, you should use it as follows for moment support.

```
{
    ignoreStringcase: obj => moment.isMoment(obj)
}
```

If you have better solutions please feel free to share them!

**Comment by Kequc** [comment]
I'm thinking of changing the implementation entirely to something simpler. I would remove the `ignoreStringcase` configuration option and use this function I found on stackoverflow that seems to work how I would like.

```javascript
function isPlainObj(o) {
  return typeof o == 'object' && o.constructor == Object;
}

isPlainObj({}); // true
isPlainObj(new Object()); // true
isPlainObj([]); // false
isPlainObj(new Date()); // false
isPlainObj(moment()); // false
```

This would be a 1.1.0 release. Can you guys think of any drawbacks to using this?

**Comment by Kequc** [comment]
In an effort to keep the library as simple as possible and fun I've added this, as above. I couldn't think of any downside. Release 1.1.0 resolves both problems in this thread.
